Python数据分析入门

1、创建一个数组

In [2]:
import numpy as np

#通过np.array函数，从list中创建
list1=[1,2,3,4,5,6]
np.array(list1) #可以传入多个列表

array([1, 2, 3, 4, 5, 6])

In [4]:
#通过np.zeros和np.ones函数，创建全0或全1数组，默认数据类型为float
np.zeros(shape=(2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
#通过np.arange函数，创建arange参数指定的数组
import numpy as np

np.arange(0,10,0.5).reshape(4,5) #(起始值,结束值-1,步长).reshape(行数,列数），步长可以为float值

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [7]:
#通过np.random.rand(N)，创建一个具有N个元素的0<=X<1的数组
np.random.rand(10)

array([0.54688303, 0.44256043, 0.76983641, 0.13448036, 0.89693116,
       0.78121554, 0.55314484, 0.37609256, 0.31052419, 0.8384218 ])

In [8]:
#通过np.random.randint(N)，创建一个0－9之间任意整数
np.random.randint(10)

8

2、查看数组对象的属性 

In [9]:
#ndim：查看数组的维度（一维、二维…………）
#shape：查看数组的大小（几行，几列）
#size：查看数组元素的个数
#dtype：查看数组元素的数据类型

3、访问数组

In [19]:
#访问数组中的某个数据：数组名[行，列]
#访问数组中的某连续区域的数据：数组名[开始行:结束列-1:步长,开始行:结束列-1:步长]
a=np.array([[1,2,3]
           ,[4,5,6]
           ,[7,8,9]])
#访问a数组中的5,6,8,9
a[:2,:2]

array([[1, 2],
       [4, 5]])

4、数组之间的运算

In [7]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(1,10).reshape(3,3)

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#数组之间的加、减运算：参加运算的数组的行与列的个数必须相同，它们的对应位置执行相应的操作。
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [13]:
#数组之间的相乘、相除操作了是它们的对应位置执行相应的操作，但在相除操作中，除数的数组元素可能为0，因此不建议用数组做相除操作。
a*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

5、矩阵之间运算

In [14]:
#矩阵是特殊的二维数组，但数组可以是一维或多维；
#它没有加、减、乘、除等运算，它有专门的矩阵运算，如矩阵乘法（不是对应元素相乘）、转置、求逆等运算；
#矩阵是数组的子集

In [15]:
matrix_a=np.matrix(a)
matrix_a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [2]:
import numpy as np
#矩阵之间的乘法：a.dot(b)，矩阵a的列数必须一矩阵b的行数一至
a=np.matrix(np.arange(12).reshape(3,4))
b=np.matrix(np.arange(12).reshape(4,3))

In [3]:
a

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [4]:
b

matrix([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [6]:
a.dot(b)

matrix([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262]])

6、数组的合并

In [7]:
#np.concatenate合并数组，参数axis＝0时为垂直方向合并，axis=1时为水平方向
a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)
c=np.arange(10).reshape(2,5)

In [8]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b

array([[0, 1, 2]])

In [10]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
np.concatenate([a,b],axis=0) #当axis=0时，合并的数组列数要相同；

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

In [14]:
np.concatenate([a,c],axis=1) #当axis=1时，合并的数组行数要相同；

array([[0, 1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 5, 6, 7, 8, 9]])

在只合并二维数组时，用vstack（行方向）和hstack（列方向）方法也可实现。

In [15]:
np.vstack([a,b])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

In [16]:
np.hstack([a,c])

array([[0, 1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 5, 6, 7, 8, 9]])

7、数组的分割

In [24]:
#np.split()实现数组分割，它的参数indices_or_sections为整数（必须可以整除）或一维数组
ary=np.arange(15)

In [29]:
np.split(ary,5)

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11]),
 array([12, 13, 14])]

In [30]:
np.split(ary,[2,5])

[array([0, 1]),
 array([2, 3, 4]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])]

8、Numpy的聚合运算

In [8]:
#单一维度的聚合：sum、min、max

a=np.arange(10)

In [9]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.sum(a)

45

In [11]:
a.sum()

45

In [12]:
np.min(a)

0

In [13]:
a.min()

0

In [14]:
np.max(a)

9

In [15]:
a.max()

9

In [21]:
#多维度聚合，一行一行或一列一列地做相应地操作
ary=np.arange(16).reshape(4,4)

In [22]:
ary

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
np.sum(ary,axis=0) #axis=0时，则沿着横轴方向（看纵轴）

array([24, 28, 32, 36])

In [26]:
np.sum(ary,axis=1) #axis=1时，则沿着纵轴方向（看横轴）

array([ 6, 22, 38, 54])

In [28]:
np.min(ary,axis=0)

array([0, 1, 2, 3])

In [29]:
np.min(ary,axis=1)

array([ 0,  4,  8, 12])

In [30]:
#max、mean(均值)

Numpy的其它操作

In [32]:
# argmin／argmax返回数组最小值／最大值的index

a=np.random.random(20)

In [33]:
a

array([0.00986201, 0.85856264, 0.4466069 , 0.54954499, 0.66196761,
       0.62035462, 0.02374403, 0.60184331, 0.00756412, 0.82644067,
       0.07731234, 0.90073929, 0.09398673, 0.91223261, 0.16936361,
       0.04951422, 0.33931149, 0.72876231, 0.71486854, 0.97866573])

In [34]:
np.argmin(a)

8

In [35]:
np.min(a)

0.007564122099009696

In [36]:
# shuffle打乱数组排序

a=np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
np.random.shuffle(a)
a

array([[15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
np.sort(a,axis=1)

array([[15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
# 数组的筛选

a[a%2==0]

array([16, 18,  0,  2,  4,  6,  8, 10, 12, 14])

In [46]:
a[(a>=3) & (a<10)]

array([3, 4, 5, 6, 7, 8, 9])

# 练习

In [6]:
import numpy as np

def numpy_sum(n):
    a=np.arange(n)**2
    b=np.arange(n)**3
    return a+b

def python_num(n):
    a=[i**2 for i in range(n)]
    b=[i**3 for i in range(n)]
    ab_sum=[]
    for i in range(n):
        ab_sum.append(a[i]+b[i])
    return ab_sum


%timeit numpy_sum(100)
%timeit python_num(100)

4.57 µs ± 147 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
68.7 µs ± 1.62 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [14]:
np.array([[1,2,3],[4,5,6]],ndmin=2)+2.5 #np.array()的参数必须是一个可迭代对象

array([[3.5, 4.5, 5.5],
       [6.5, 7.5, 8.5]])

In [3]:
import numpy as np

a=np.arange(0,201.0,3.0)
len(a)

67

In [5]:
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None) #建立等差数列

# start: 序列起始值
# stop: 序列终止值, 当endpoint=True时,该值包含于数列中
# num: 样本数量, 默认为50
# endpoint: 默认为True时,数列包含stop值, 否则不包含
# retstep: 为True时, 生成的数组会显示间距, 默认不显示
# dtype: ndarray的数据类型

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
np.logspace(start, stop, num=50, endpoint=True, base=D, dtype=None) #建立等比数列

# start: 序列起始值, 生成数组的起始值为D的start次方
# stop: 序列终止值, 当endpoint=True时,该值包含于数列中, 生成数组的起始值为D的stop次方
# num: 样本数量, 默认为50
# endpoint: 默认为True时,数列包含stop值, 否则不包含
# base: 对数log的底数, 默认为10
# dtype: ndarray的数据类型

In [21]:
day=30
day_payments=np.logspace(0,29,i,base=2)*0.01
total_payments=np.sum(day_payments)

for day, payment in enumerate(day_payments, start=1):  
    print(f"Day {day}: {payment:.2f} yuan")  

print(f"Total payment after {day} days: {total_payments:.2f} yuan")  

Day 1: 0.01 yuan
Day 2: 0.02 yuan
Day 3: 0.04 yuan
Day 4: 0.08 yuan
Day 5: 0.16 yuan
Day 6: 0.32 yuan
Day 7: 0.64 yuan
Day 8: 1.28 yuan
Day 9: 2.56 yuan
Day 10: 5.12 yuan
Day 11: 10.24 yuan
Day 12: 20.48 yuan
Day 13: 40.96 yuan
Day 14: 81.92 yuan
Day 15: 163.84 yuan
Day 16: 327.68 yuan
Day 17: 655.36 yuan
Day 18: 1310.72 yuan
Day 19: 2621.44 yuan
Day 20: 5242.88 yuan
Day 21: 10485.76 yuan
Day 22: 20971.52 yuan
Day 23: 41943.04 yuan
Day 24: 83886.08 yuan
Day 25: 167772.16 yuan
Day 26: 335544.32 yuan
Day 27: 671088.64 yuan
Day 28: 1342177.28 yuan
Day 29: 2684354.56 yuan
Day 30: 5368709.12 yuan
Total payment after 30 days: 10737418.23 yuan
